// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	announcement "app/internal/handler/announcement"
	auth "app/internal/handler/auth"
	health "app/internal/handler/health"
	markdown "app/internal/handler/markdown"
	rbac "app/internal/handler/rbac"
	user "app/internal/handler/user"
	"app/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/announcement/create",
				Handler: announcement.CreateAnnouncementHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/announcement/delete/:announcementId",
				Handler: announcement.DeleteAnnouncementHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/announcement/update/:announcementId",
				Handler: announcement.UpdateAnnouncementHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/announcement/list",
				Handler: announcement.ListAnnouncementsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/announcement/preview/:announcementId",
				Handler: announcement.PreviewAnnouncementHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/refresh",
				Handler: auth.RefreshTokenHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Refresh.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/status/healthz",
				Handler: health.HealthzHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/status/readyz",
				Handler: health.ReadyzHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
		rest.WithSSE(),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/markdown/review/:markdownId",
				Handler: markdown.GetReviewInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/markdown/review/:markdownId",
				Handler: markdown.ReviewMarkdownHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/markdown/reviews",
				Handler: markdown.ListReviewsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/markdown/unreviewed",
				Handler: markdown.ListUnreviewedMarkdownsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/markdown/list",
				Handler: markdown.ListMarkdownsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/markdown/list/:userId",
				Handler: markdown.MineMarkdownHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/markdown/preview/:markdownId",
				Handler: markdown.PreviewMarkdownHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodDelete,
				Path:    "/markdown/delete/:markdownId",
				Handler: markdown.DeleteMarkdownHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/markdown/update/:markdownId",
				Handler: markdown.UpdateMarkdownHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/markdown/upload",
				Handler: markdown.UploadMarkdownHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/rbac/permissions/assign/:permissionId",
				Handler: rbac.AssignRolePermissionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/rbac/permissions/create",
				Handler: rbac.CreatePermissionHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/rbac/permissions/delete/:permissionId",
				Handler: rbac.DeletePermissionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/rbac/permissions/list",
				Handler: rbac.ListPermissionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/rbac/permissions/update/:permissionId",
				Handler: rbac.UpdatePermissionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/rbac/roles/assign/:userId",
				Handler: rbac.AssignUserRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/rbac/roles/create",
				Handler: rbac.CreateRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/rbac/roles/delete/:roleId",
				Handler: rbac.DeleteRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/rbac/roles/list",
				Handler: rbac.ListRolesHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/rbac/roles/update/:roleId",
				Handler: rbac.UpdateRoleHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/logout/:userId",
				Handler: user.LogoutHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/profile/:userId",
				Handler: user.GetProfileHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
