// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package rbac

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	permissionFieldNames          = builder.RawFieldNames(&Permission{})
	permissionRows                = strings.Join(permissionFieldNames, ",")
	permissionRowsExpectAutoSet   = strings.Join(stringx.Remove(permissionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	permissionRowsWithPlaceHolder = strings.Join(stringx.Remove(permissionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePermissionIdPrefix             = "cache:permission:id:"
	cachePermissionResourceActionPrefix = "cache:permission:resource:action:"
)

type (
	permissionModel interface {
		Insert(ctx context.Context, data *Permission) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Permission, error)
		FindOneByResourceAction(ctx context.Context, resource string, action string) (*Permission, error)
		Update(ctx context.Context, data *Permission) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPermissionModel struct {
		sqlc.CachedConn
		table string
	}

	Permission struct {
		Id       int64  `db:"id"`       // 内部主键
		Resource string `db:"resource"` // 资源标识
		Action   string `db:"action"`   // 操作类型
		Label    string `db:"label"`    // 权限名称
	}
)

func newPermissionModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPermissionModel {
	return &defaultPermissionModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`permission`",
	}
}

func (m *defaultPermissionModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	permissionIdKey := fmt.Sprintf("%s%v", cachePermissionIdPrefix, id)
	permissionResourceActionKey := fmt.Sprintf("%s%v:%v", cachePermissionResourceActionPrefix, data.Resource, data.Action)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, permissionIdKey, permissionResourceActionKey)
	return err
}

func (m *defaultPermissionModel) FindOne(ctx context.Context, id int64) (*Permission, error) {
	permissionIdKey := fmt.Sprintf("%s%v", cachePermissionIdPrefix, id)
	var resp Permission
	err := m.QueryRowCtx(ctx, &resp, permissionIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", permissionRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPermissionModel) FindOneByResourceAction(ctx context.Context, resource string, action string) (*Permission, error) {
	permissionResourceActionKey := fmt.Sprintf("%s%v:%v", cachePermissionResourceActionPrefix, resource, action)
	var resp Permission
	err := m.QueryRowIndexCtx(ctx, &resp, permissionResourceActionKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `resource` = ? and `action` = ? limit 1", permissionRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, resource, action); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPermissionModel) Insert(ctx context.Context, data *Permission) (sql.Result, error) {
	permissionIdKey := fmt.Sprintf("%s%v", cachePermissionIdPrefix, data.Id)
	permissionResourceActionKey := fmt.Sprintf("%s%v:%v", cachePermissionResourceActionPrefix, data.Resource, data.Action)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, permissionRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Resource, data.Action, data.Label)
	}, permissionIdKey, permissionResourceActionKey)
	return ret, err
}

func (m *defaultPermissionModel) Update(ctx context.Context, newData *Permission) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	permissionIdKey := fmt.Sprintf("%s%v", cachePermissionIdPrefix, data.Id)
	permissionResourceActionKey := fmt.Sprintf("%s%v:%v", cachePermissionResourceActionPrefix, data.Resource, data.Action)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, permissionRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Resource, newData.Action, newData.Label, newData.Id)
	}, permissionIdKey, permissionResourceActionKey)
	return err
}

func (m *defaultPermissionModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePermissionIdPrefix, primary)
}

func (m *defaultPermissionModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", permissionRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPermissionModel) tableName() string {
	return m.table
}
