// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package rbac

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	permissionsFieldNames          = builder.RawFieldNames(&Permissions{})
	permissionsRows                = strings.Join(permissionsFieldNames, ",")
	permissionsRowsExpectAutoSet   = strings.Join(stringx.Remove(permissionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	permissionsRowsWithPlaceHolder = strings.Join(stringx.Remove(permissionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePermissionsIdPrefix             = "cache:permissions:id:"
	cachePermissionsResourceActionPrefix = "cache:permissions:resource:action:"
)

type (
	permissionsModel interface {
		Insert(ctx context.Context, data *Permissions) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Permissions, error)
		FindOneByResourceAction(ctx context.Context, resource string, action string) (*Permissions, error)
		Update(ctx context.Context, data *Permissions) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPermissionsModel struct {
		sqlc.CachedConn
		table string
	}

	Permissions struct {
		Id       int64  `db:"id"`       // 内部主键
		Resource string `db:"resource"` // 资源标识
		Action   string `db:"action"`   // 操作类型
		Label    string `db:"label"`    // 权限名称
	}
)

func newPermissionsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPermissionsModel {
	return &defaultPermissionsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`permission`",
	}
}

func (m *defaultPermissionsModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	permissionsIdKey := fmt.Sprintf("%s%v", cachePermissionsIdPrefix, id)
	permissionsResourceActionKey := fmt.Sprintf("%s%v:%v", cachePermissionsResourceActionPrefix, data.Resource, data.Action)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, permissionsIdKey, permissionsResourceActionKey)
	return err
}

func (m *defaultPermissionsModel) FindOne(ctx context.Context, id int64) (*Permissions, error) {
	permissionsIdKey := fmt.Sprintf("%s%v", cachePermissionsIdPrefix, id)
	var resp Permissions
	err := m.QueryRowCtx(ctx, &resp, permissionsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", permissionsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPermissionsModel) FindOneByResourceAction(ctx context.Context, resource string, action string) (*Permissions, error) {
	permissionsResourceActionKey := fmt.Sprintf("%s%v:%v", cachePermissionsResourceActionPrefix, resource, action)
	var resp Permissions
	err := m.QueryRowIndexCtx(ctx, &resp, permissionsResourceActionKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `resource` = ? and `action` = ? limit 1", permissionsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, resource, action); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPermissionsModel) Insert(ctx context.Context, data *Permissions) (sql.Result, error) {
	permissionsIdKey := fmt.Sprintf("%s%v", cachePermissionsIdPrefix, data.Id)
	permissionsResourceActionKey := fmt.Sprintf("%s%v:%v", cachePermissionsResourceActionPrefix, data.Resource, data.Action)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, permissionsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Resource, data.Action, data.Label)
	}, permissionsIdKey, permissionsResourceActionKey)
	return ret, err
}

func (m *defaultPermissionsModel) Update(ctx context.Context, newData *Permissions) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	permissionsIdKey := fmt.Sprintf("%s%v", cachePermissionsIdPrefix, data.Id)
	permissionsResourceActionKey := fmt.Sprintf("%s%v:%v", cachePermissionsResourceActionPrefix, data.Resource, data.Action)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, permissionsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Resource, newData.Action, newData.Label, newData.Id)
	}, permissionsIdKey, permissionsResourceActionKey)
	return err
}

func (m *defaultPermissionsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePermissionsIdPrefix, primary)
}

func (m *defaultPermissionsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", permissionsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPermissionsModel) tableName() string {
	return m.table
}
