// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package rbac

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	rolesFieldNames          = builder.RawFieldNames(&Roles{})
	rolesRows                = strings.Join(rolesFieldNames, ",")
	rolesRowsExpectAutoSet   = strings.Join(stringx.Remove(rolesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	rolesRowsWithPlaceHolder = strings.Join(stringx.Remove(rolesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRolesIdPrefix   = "cache:roles:id:"
	cacheRolesNamePrefix = "cache:roles:name:"
)

type (
	rolesModel interface {
		Insert(ctx context.Context, data *Roles) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Roles, error)
		FindOneByName(ctx context.Context, name string) (*Roles, error)
		Update(ctx context.Context, data *Roles) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRolesModel struct {
		sqlc.CachedConn
		table string
	}

	Roles struct {
		Id          int64        `db:"id"`          // 内部主键
		Name        string       `db:"name"`        // 角色名称
		Description string       `db:"description"` // 角色描述
		DeletedAt   sql.NullTime `db:"deleted_at"`
	}
)

func newRolesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultRolesModel {
	return &defaultRolesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`role`",
	}
}

func (m *defaultRolesModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rolesIdKey := fmt.Sprintf("%s%v", cacheRolesIdPrefix, id)
	rolesNameKey := fmt.Sprintf("%s%v", cacheRolesNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rolesIdKey, rolesNameKey)
	return err
}

func (m *defaultRolesModel) FindOne(ctx context.Context, id int64) (*Roles, error) {
	rolesIdKey := fmt.Sprintf("%s%v", cacheRolesIdPrefix, id)
	var resp Roles
	err := m.QueryRowCtx(ctx, &resp, rolesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", rolesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRolesModel) FindOneByName(ctx context.Context, name string) (*Roles, error) {
	rolesNameKey := fmt.Sprintf("%s%v", cacheRolesNamePrefix, name)
	var resp Roles
	err := m.QueryRowIndexCtx(ctx, &resp, rolesNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", rolesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRolesModel) Insert(ctx context.Context, data *Roles) (sql.Result, error) {
	rolesIdKey := fmt.Sprintf("%s%v", cacheRolesIdPrefix, data.Id)
	rolesNameKey := fmt.Sprintf("%s%v", cacheRolesNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, rolesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Description, data.DeletedAt)
	}, rolesIdKey, rolesNameKey)
	return ret, err
}

func (m *defaultRolesModel) Update(ctx context.Context, newData *Roles) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rolesIdKey := fmt.Sprintf("%s%v", cacheRolesIdPrefix, data.Id)
	rolesNameKey := fmt.Sprintf("%s%v", cacheRolesNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, rolesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.Description, newData.DeletedAt, newData.Id)
	}, rolesIdKey, rolesNameKey)
	return err
}

func (m *defaultRolesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRolesIdPrefix, primary)
}

func (m *defaultRolesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", rolesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultRolesModel) tableName() string {
	return m.table
}
