// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package rbac

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	rolePermissionFieldNames          = builder.RawFieldNames(&RolePermission{})
	rolePermissionRows                = strings.Join(rolePermissionFieldNames, ",")
	rolePermissionRowsExpectAutoSet   = strings.Join(stringx.Remove(rolePermissionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	rolePermissionRowsWithPlaceHolder = strings.Join(stringx.Remove(rolePermissionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRolePermissionIdPrefix                 = "cache:rolePermission:id:"
	cacheRolePermissionRoleIdPermissionIdPrefix = "cache:rolePermission:roleId:permissionId:"
)

type (
	rolePermissionModel interface {
		Insert(ctx context.Context, data *RolePermission) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*RolePermission, error)
		FindOneByRoleIdPermissionId(ctx context.Context, roleId int64, permissionId int64) (*RolePermission, error)
		Update(ctx context.Context, data *RolePermission) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRolePermissionModel struct {
		sqlc.CachedConn
		table string
	}

	RolePermission struct {
		Id           int64 `db:"id"`            // 内部主键
		RoleId       int64 `db:"role_id"`       // 角色内部ID (→ roles.id)
		PermissionId int64 `db:"permission_id"` // 权限内部ID (→ permissions.id)
	}
)

func newRolePermissionModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultRolePermissionModel {
	return &defaultRolePermissionModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`role_permission`",
	}
}

func (m *defaultRolePermissionModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	rolePermissionIdKey := fmt.Sprintf("%s%v", cacheRolePermissionIdPrefix, id)
	rolePermissionRoleIdPermissionIdKey := fmt.Sprintf("%s%v:%v", cacheRolePermissionRoleIdPermissionIdPrefix, data.RoleId, data.PermissionId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, rolePermissionIdKey, rolePermissionRoleIdPermissionIdKey)
	return err
}

func (m *defaultRolePermissionModel) FindOne(ctx context.Context, id int64) (*RolePermission, error) {
	rolePermissionIdKey := fmt.Sprintf("%s%v", cacheRolePermissionIdPrefix, id)
	var resp RolePermission
	err := m.QueryRowCtx(ctx, &resp, rolePermissionIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", rolePermissionRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRolePermissionModel) FindOneByRoleIdPermissionId(ctx context.Context, roleId int64, permissionId int64) (*RolePermission, error) {
	rolePermissionRoleIdPermissionIdKey := fmt.Sprintf("%s%v:%v", cacheRolePermissionRoleIdPermissionIdPrefix, roleId, permissionId)
	var resp RolePermission
	err := m.QueryRowIndexCtx(ctx, &resp, rolePermissionRoleIdPermissionIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `role_id` = ? and `permission_id` = ? limit 1", rolePermissionRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, roleId, permissionId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRolePermissionModel) Insert(ctx context.Context, data *RolePermission) (sql.Result, error) {
	rolePermissionIdKey := fmt.Sprintf("%s%v", cacheRolePermissionIdPrefix, data.Id)
	rolePermissionRoleIdPermissionIdKey := fmt.Sprintf("%s%v:%v", cacheRolePermissionRoleIdPermissionIdPrefix, data.RoleId, data.PermissionId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, rolePermissionRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.RoleId, data.PermissionId)
	}, rolePermissionIdKey, rolePermissionRoleIdPermissionIdKey)
	return ret, err
}

func (m *defaultRolePermissionModel) Update(ctx context.Context, newData *RolePermission) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	rolePermissionIdKey := fmt.Sprintf("%s%v", cacheRolePermissionIdPrefix, data.Id)
	rolePermissionRoleIdPermissionIdKey := fmt.Sprintf("%s%v:%v", cacheRolePermissionRoleIdPermissionIdPrefix, data.RoleId, data.PermissionId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, rolePermissionRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.RoleId, newData.PermissionId, newData.Id)
	}, rolePermissionIdKey, rolePermissionRoleIdPermissionIdKey)
	return err
}

func (m *defaultRolePermissionModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRolePermissionIdPrefix, primary)
}

func (m *defaultRolePermissionModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", rolePermissionRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultRolePermissionModel) tableName() string {
	return m.table
}
