// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package rbac

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userRolesFieldNames          = builder.RawFieldNames(&UserRoles{})
	userRolesRows                = strings.Join(userRolesFieldNames, ",")
	userRolesRowsExpectAutoSet   = strings.Join(stringx.Remove(userRolesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userRolesRowsWithPlaceHolder = strings.Join(stringx.Remove(userRolesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserRolesIdPrefix           = "cache:userRoles:id:"
	cacheUserRolesUserIdRoleIdPrefix = "cache:userRoles:userId:roleId:"
)

type (
	userRolesModel interface {
		Insert(ctx context.Context, data *UserRoles) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserRoles, error)
		FindOneByUserIdRoleId(ctx context.Context, userId string, roleId int64) (*UserRoles, error)
		Update(ctx context.Context, data *UserRoles) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserRolesModel struct {
		sqlc.CachedConn
		table string
	}

	UserRoles struct {
		Id     int64  `db:"id"`      // 内部主键
		UserId string `db:"user_id"` // 用户UUID (→ users.user_id)
		RoleId int64  `db:"role_id"` // 角色内部ID (→ roles.id)
	}
)

func newUserRolesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserRolesModel {
	return &defaultUserRolesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_role`",
	}
}

func (m *defaultUserRolesModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	userRolesIdKey := fmt.Sprintf("%s%v", cacheUserRolesIdPrefix, id)
	userRolesUserIdRoleIdKey := fmt.Sprintf("%s%v:%v", cacheUserRolesUserIdRoleIdPrefix, data.UserId, data.RoleId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userRolesIdKey, userRolesUserIdRoleIdKey)
	return err
}

func (m *defaultUserRolesModel) FindOne(ctx context.Context, id int64) (*UserRoles, error) {
	userRolesIdKey := fmt.Sprintf("%s%v", cacheUserRolesIdPrefix, id)
	var resp UserRoles
	err := m.QueryRowCtx(ctx, &resp, userRolesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRolesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserRolesModel) FindOneByUserIdRoleId(ctx context.Context, userId string, roleId int64) (*UserRoles, error) {
	userRolesUserIdRoleIdKey := fmt.Sprintf("%s%v:%v", cacheUserRolesUserIdRoleIdPrefix, userId, roleId)
	var resp UserRoles
	err := m.QueryRowIndexCtx(ctx, &resp, userRolesUserIdRoleIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `role_id` = ? limit 1", userRolesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, roleId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserRolesModel) Insert(ctx context.Context, data *UserRoles) (sql.Result, error) {
	userRolesIdKey := fmt.Sprintf("%s%v", cacheUserRolesIdPrefix, data.Id)
	userRolesUserIdRoleIdKey := fmt.Sprintf("%s%v:%v", cacheUserRolesUserIdRoleIdPrefix, data.UserId, data.RoleId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, userRolesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.RoleId)
	}, userRolesIdKey, userRolesUserIdRoleIdKey)
	return ret, err
}

func (m *defaultUserRolesModel) Update(ctx context.Context, newData *UserRoles) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	userRolesIdKey := fmt.Sprintf("%s%v", cacheUserRolesIdPrefix, data.Id)
	userRolesUserIdRoleIdKey := fmt.Sprintf("%s%v:%v", cacheUserRolesUserIdRoleIdPrefix, data.UserId, data.RoleId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userRolesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.RoleId, newData.Id)
	}, userRolesIdKey, userRolesUserIdRoleIdKey)
	return err
}

func (m *defaultUserRolesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserRolesIdPrefix, primary)
}

func (m *defaultUserRolesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRolesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserRolesModel) tableName() string {
	return m.table
}
