// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AnnouncementDetail struct {
	AnnouncementId string `json:"announcementId"`
	AnnouceUserId  string `json:"annouceUserId,optional"`
	Title          string `json:"title"`
	Content        string `json:"content"`
	CreatedAt      string `json:"createdAt"`
	UpdatedAt      string `json:"updatedAt"`
}

type AnnouncementListItem struct {
	AnnouncementId string `json:"announcementId"`
	AnnouceUserId  string `json:"annouceUserId,optional"`
	Title          string `json:"title"`
	CreatedAt      string `json:"createdAt"`
	UpdatedAt      string `json:"updatedAt"`
}

type AnnouncementListItemList struct {
	AnnouncementList []AnnouncementListItem `json:"announcementList"`
}

type AssignRolePermissionReq struct {
	RoleId      int64   `path:"roleId"`
	Permissions []int64 `json:"permissions"`
}

type AssignRolePermissionResp struct {
	BaseResp
	AssignRolePermissionRespBody
}

type AssignRolePermissionRespBody struct {
	Role           Role           `json:"role"`
	PermissionList PermissionList `json:"permissionList"`
}

type AssignUserRoleReq struct {
	UserId string  `path:"userId"`
	Roles  []int64 `json:"roles"`
}

type AssignUserRoleResp struct {
	BaseResp
}

type BaseResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type CreateAnnouncementReq struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type CreateAnnouncementResp struct {
	BaseResp
	CreateAnnouncementRespBody
}

type CreateAnnouncementRespBody struct {
	Announcement AnnouncementDetail `json:"announcement"`
}

type CreatePermissionReq struct {
	Permission Permission `json:"permission"`
}

type CreatePermissionResp struct {
	BaseResp
	CreatePermissionRespBody
}

type CreatePermissionRespBody struct {
	Permission Permission `json:"permission"`
}

type CreateRoleReq struct {
	RoleId      int64   `json:"roleId"`
	RoleName    string  `json:"name,optional"`
	Description string  `json:"description,optional"`
	Permissions []int64 `json:"permissions,optional"`
}

type CreateRoleResp struct {
	BaseResp
	CreateRoleRespBody
}

type CreateRoleRespBody struct {
	Role Role `json:"role"`
}

type DeleteAnnouncementReq struct {
	AnnouncementId string `path:"announcementId"`
}

type DeleteAnnouncementResp struct {
	BaseResp
}

type DeleteMarkdownReq struct {
	MarkdownId string `path:"markdownId"`
}

type DeleteMarkdownResp struct {
	BaseResp
}

type DeletePermissionReq struct {
	PermissionId int64 `path:"permissionId"`
}

type DeletePermissionResp struct {
	BaseResp
}

type DeleteRoleReq struct {
	RoleId int64 `path:"roleId"`
}

type DeleteRoleResp struct {
	BaseResp
}

type DownloadMarkdownReq struct {
	MarkdownId string `path:"markdownId"`
}

type DownloadMarkdownResp struct {
	BaseResp
}

type GetReviewInfoReq struct {
	MarkdownId string `path:"markdownId"`
}

type GetReviewInfoResp struct {
	BaseResp
	GetReviewInfoRespBody
}

type GetReviewInfoRespBody struct {
	MarkdownId    string `json:"markdownId"`
	ReviewerId    string `json:"reviewerId"`
	ReviewStatus  string `json:"reviewStatus"`
	ReviewComment string `json:"reviewComment"`
	ReviewAt      string `json:"reviewAt"`
}

type ListAnnouncementReq struct {
	PageRequest
}

type ListAnnouncementResp struct {
	BaseResp
	PageInfo
	ListAnnouncementRespBody
}

type ListAnnouncementRespBody struct {
	AnnouncementList AnnouncementListItemList `json:"announcementList"`
}

type ListMarkdownReq struct {
	PageRequest
}

type ListMarkdownResp struct {
	BaseResp
	PageInfo
	ListMarkdownRespBody
}

type ListMarkdownRespBody struct {
	MarkdownList MarkdownListItemList `json:"markdownList"`
}

type ListPermissionResp struct {
	BaseResp
	PageInfo
	ListPermissionRespBody
}

type ListPermissionRespBody struct {
	PermissionList PermissionList `json:"permissionList"`
}

type ListPermissionsReq struct {
	PageRequest
}

type ListReviewReq struct {
	PageRequest
	Status string `form:"status,optional"` // pending|approved|rejected，空=全部
}

type ListReviewResp struct {
	BaseResp
	PageInfo
	ListReviewRespBody
}

type ListReviewRespBody struct {
	MarkdownList MarkdownListItemList `json:"markdownList"`
}

type ListRoleResp struct {
	BaseResp
	PageInfo
	ListRoleRespBody
}

type ListRoleRespBody struct {
	RoleList RoleList `json:"roleList"`
}

type ListRolesReq struct {
	PageRequest
}

type LoginReq struct {
	UserEmail    string `json:"userEmail"`
	UserPassword string `json:"userPassword"`
}

type LoginResp struct {
	BaseResp
	LoginRespBody
}

type LoginRespBody struct {
	AccessToken  string   `json:"accessToken"`
	RefreshToken string   `json:"refreshToken"`
	ExpiresIn    int64    `json:"expiresIn"`
	UserInfo     UserInfo `json:"userInfo"`
}

type LogoutReq struct {
	UserId string `path:"userId"`
}

type LogoutResp struct {
	BaseResp
}

type MarkdownDetail struct {
	MarkdownId    string `json:"markdownId"`
	AuthorId      string `json:"authorId"`
	Title         string `json:"title"`
	Summary       string `json:"summary"`
	Content       string `json:"content"`
	ReviewerId    string `json:"reviewerId,optional"`
	ReviewStatus  string `json:"reviewStatus,optional"`
	ReviewComment string `json:"reviewComment,optional"`
	CreatedAt     string `json:"createdAt"`
	UpdatedAt     string `json:"updatedAt"`
}

type MarkdownListItem struct {
	MarkdownId    string `json:"markdownId"`
	AuthorId      string `json:"authorId"`
	Title         string `json:"title"`
	Summary       string `json:"summary"`
	ReviewerId    string `json:"reviewerId,optional"`
	ReviewStatus  string `json:"reviewStatus,optional"`
	ReviewComment string `json:"reviewComment,optional"`
	CreatedAt     string `json:"createdAt"`
	UpdatedAt     string `json:"updatedAt"`
}

type MarkdownListItemList struct {
	MarkdownList []MarkdownListItem `json:"markdownList"`
}

type MineMarkdownReq struct {
	UserId string `path:"userId"`
	PageRequest
	ReviewStatus string `form:"reviewStatus,optional"`
}

type PageInfo struct {
	TotalCount int64 `json:"totalCount,optional"`
	PageNumber int   `json:"page"`
	PageSize   int   `json:"pageSize"`
}

type PageRequest struct {
	PageNumber int `form:"page,default=1"`
	PageSize   int `form:"pageSize,default=10"`
}

type Permission struct {
	PermissionId int64  `json:"permissionId"`
	Resource     string `json:"resource"`
	Action       string `json:"action"`
	Label        string `json:"label"`
}

type PermissionList struct {
	PermissionList []Permission `json:"permissionList"`
}

type PreviewAnnouncementReq struct {
	AnnouncementId string `path:"announcementId"`
}

type PreviewAnnouncementResp struct {
	BaseResp
	PreviewAnnouncementRespBody
}

type PreviewAnnouncementRespBody struct {
	Announcement AnnouncementDetail `json:"announcement"`
}

type PreviewMarkdownReq struct {
	MarkdownId string `path:"markdownId"`
}

type PreviewMarkdownResp struct {
	BaseResp
	PreviewMarkdownRespBody
}

type PreviewMarkdownRespBody struct {
	Markdown MarkdownDetail `json:"markdown"`
}

type RefreshReq struct {
	RefreshToken string `json:"refreshToken"`
}

type RegisterInfo struct {
	UserName     string `json:"userName"`
	UserPassword string `json:"userPassword"`
	Email        string `json:"email"`
}

type RegisterReq struct {
	RegisterInfo RegisterInfo `json:"registerInfo"`
}

type RegisterResp struct {
	BaseResp
	RegisterRespBody
}

type RegisterRespBody struct {
	RegisteredInfo RegisteredInfo `json:"registeredInfo"`
}

type RegisteredInfo struct {
	UserId   string `json:"userId"`
	UserName string `json:"userName"`
	Email    string `json:"email"`
}

type ReviewMarkdownReq struct {
	MarkdownId string `path:"markdownId"`
	Status     string `json:"status"`
	Comment    string `json:"comment,optional"`
}

type ReviewMarkdownResp struct {
	BaseResp
	ReviewMarkdownRespBody
}

type ReviewMarkdownRespBody struct {
	MarkdownId string `json:"markdownId"`
	AuthorId   string `json:"authorId"`
	Status     string `json:"status"`
	Comment    string `json:"comment,optional"`
}

type Role struct {
	RoleId      int64   `json:"roleId"`
	RoleName    string  `json:"name,optional"`
	Description string  `json:"description"`
	Permissions []int64 `json:"permissions"`
}

type RoleList struct {
	RoleList []Role `json:"roleList"`
}

type UpdateAnnouncementReq struct {
	AnnouncementId string `path:"announcementId"`
	Title          string `json:"title"`
	Content        string `json:"content"`
}

type UpdateAnnouncementResp struct {
	BaseResp
	UpdateAnnouncementRespBody
}

type UpdateAnnouncementRespBody struct {
	Announcement AnnouncementDetail `json:"announcement"`
}

type UpdateMarkdownReq struct {
	MarkdownId string `path:"markdownId"`
	Title      string `json:"title"`
	Content    string `json:"content"`
}

type UpdateMarkdownResp struct {
	BaseResp
	UpdateMarkdownRespBody
}

type UpdateMarkdownRespBody struct {
	Markdown MarkdownDetail `json:"markdown"`
}

type UpdatePermissionReq struct {
	PermissionId int64      `path:"permissionId"`
	Permission   Permission `json:"permission"`
}

type UpdatePermissionResp struct {
	BaseResp
	UpdatePermissionRespBody
}

type UpdatePermissionRespBody struct {
	Permission Permission `json:"permission"`
}

type UpdateRoleReq struct {
	RoleId int64 `path:"roleId"`
	Role   Role  `json:"role"`
}

type UpdateRoleResp struct {
	BaseResp
	UpdateRoleRespBody
}

type UpdateRoleRespBody struct {
	Role Role `json:"role"`
}

type UploadMarkdownReq struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type UploadMarkdownResp struct {
	BaseResp
	UploadMarkdownRespBody
}

type UploadMarkdownRespBody struct {
	Markdown MarkdownDetail `json:"markdown"`
}

type UserInfo struct {
	UserId   string `json:"userId"`
	UserName string `json:"userName"`
	Email    string `json:"email"`
	RoleId   int64  `json:"roleId"`
}

type UserProfile struct {
	UserId   string `json:"userId"`
	UserName string `json:"userName"`
	Email    string `json:"email"`
}

type UserProfileReq struct {
	UserId string `path:"userId"`
}

type UserProfileResp struct {
	BaseResp
	UserProfileRespBody
}

type UserProfileRespBody struct {
	UserProfile UserProfile `json:"userProfile"`
}
