// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package announcement

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	announcementContentFieldNames          = builder.RawFieldNames(&AnnouncementContent{})
	announcementContentRows                = strings.Join(announcementContentFieldNames, ",")
	announcementContentRowsExpectAutoSet   = strings.Join(stringx.Remove(announcementContentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	announcementContentRowsWithPlaceHolder = strings.Join(stringx.Remove(announcementContentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAnnouncementContentIdPrefix             = "cache:announcementContent:id:"
	cacheAnnouncementContentAnnouncementIdPrefix = "cache:announcementContent:announcementId:"
)

type (
	announcementContentModel interface {
		Insert(ctx context.Context, data *AnnouncementContent) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AnnouncementContent, error)
		FindOneByAnnouncementId(ctx context.Context, announcementId string) (*AnnouncementContent, error)
		Update(ctx context.Context, data *AnnouncementContent) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAnnouncementContentModel struct {
		sqlc.CachedConn
		table string
	}

	AnnouncementContent struct {
		Id             int64  `db:"id"`              // 内部主键
		AnnouncementId string `db:"announcement_id"` // 对象ID (UUIDv7)
		Content        string `db:"content"`
	}
)

func newAnnouncementContentModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAnnouncementContentModel {
	return &defaultAnnouncementContentModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`announcement_content`",
	}
}

func (m *defaultAnnouncementContentModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	announcementContentAnnouncementIdKey := fmt.Sprintf("%s%v", cacheAnnouncementContentAnnouncementIdPrefix, data.AnnouncementId)
	announcementContentIdKey := fmt.Sprintf("%s%v", cacheAnnouncementContentIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, announcementContentAnnouncementIdKey, announcementContentIdKey)
	return err
}

func (m *defaultAnnouncementContentModel) FindOne(ctx context.Context, id int64) (*AnnouncementContent, error) {
	announcementContentIdKey := fmt.Sprintf("%s%v", cacheAnnouncementContentIdPrefix, id)
	var resp AnnouncementContent
	err := m.QueryRowCtx(ctx, &resp, announcementContentIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", announcementContentRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAnnouncementContentModel) FindOneByAnnouncementId(ctx context.Context, announcementId string) (*AnnouncementContent, error) {
	announcementContentAnnouncementIdKey := fmt.Sprintf("%s%v", cacheAnnouncementContentAnnouncementIdPrefix, announcementId)
	var resp AnnouncementContent
	err := m.QueryRowIndexCtx(ctx, &resp, announcementContentAnnouncementIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `announcement_id` = ? limit 1", announcementContentRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, announcementId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAnnouncementContentModel) Insert(ctx context.Context, data *AnnouncementContent) (sql.Result, error) {
	announcementContentAnnouncementIdKey := fmt.Sprintf("%s%v", cacheAnnouncementContentAnnouncementIdPrefix, data.AnnouncementId)
	announcementContentIdKey := fmt.Sprintf("%s%v", cacheAnnouncementContentIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, announcementContentRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.AnnouncementId, data.Content)
	}, announcementContentAnnouncementIdKey, announcementContentIdKey)
	return ret, err
}

func (m *defaultAnnouncementContentModel) Update(ctx context.Context, newData *AnnouncementContent) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	announcementContentAnnouncementIdKey := fmt.Sprintf("%s%v", cacheAnnouncementContentAnnouncementIdPrefix, data.AnnouncementId)
	announcementContentIdKey := fmt.Sprintf("%s%v", cacheAnnouncementContentIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, announcementContentRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.AnnouncementId, newData.Content, newData.Id)
	}, announcementContentAnnouncementIdKey, announcementContentIdKey)
	return err
}

func (m *defaultAnnouncementContentModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAnnouncementContentIdPrefix, primary)
}

func (m *defaultAnnouncementContentModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", announcementContentRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAnnouncementContentModel) tableName() string {
	return m.table
}
