// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package announcement

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	announcementFieldNames          = builder.RawFieldNames(&Announcement{})
	announcementRows                = strings.Join(announcementFieldNames, ",")
	announcementRowsExpectAutoSet   = strings.Join(stringx.Remove(announcementFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	announcementRowsWithPlaceHolder = strings.Join(stringx.Remove(announcementFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAnnouncementIdPrefix             = "cache:announcement:id:"
	cacheAnnouncementAnnouncementIdPrefix = "cache:announcement:announcementId:"
)

type (
	announcementModel interface {
		Insert(ctx context.Context, data *Announcement) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Announcement, error)
		FindOneByAnnouncementId(ctx context.Context, announcementId string) (*Announcement, error)
		Update(ctx context.Context, data *Announcement) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAnnouncementModel struct {
		sqlc.CachedConn
		table string
	}

	Announcement struct {
		Id             int64        `db:"id"`              // 内部主键
		AnnouceUserId  string       `db:"annouce_user_id"` // 发布人 users.user_id (UUIDv7)
		AnnouncementId string       `db:"announcement_id"` // 对象ID (UUIDv7)
		Title          string       `db:"title"`
		CreatedAt      time.Time    `db:"created_at"`
		UpdatedAt      time.Time    `db:"updated_at"`
		DeletedAt      sql.NullTime `db:"deleted_at"`
	}
)

func newAnnouncementModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAnnouncementModel {
	return &defaultAnnouncementModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`announcement`",
	}
}

func (m *defaultAnnouncementModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	announcementAnnouncementIdKey := fmt.Sprintf("%s%v", cacheAnnouncementAnnouncementIdPrefix, data.AnnouncementId)
	announcementIdKey := fmt.Sprintf("%s%v", cacheAnnouncementIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, announcementAnnouncementIdKey, announcementIdKey)
	return err
}

func (m *defaultAnnouncementModel) FindOne(ctx context.Context, id int64) (*Announcement, error) {
	announcementIdKey := fmt.Sprintf("%s%v", cacheAnnouncementIdPrefix, id)
	var resp Announcement
	err := m.QueryRowCtx(ctx, &resp, announcementIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", announcementRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAnnouncementModel) FindOneByAnnouncementId(ctx context.Context, announcementId string) (*Announcement, error) {
	announcementAnnouncementIdKey := fmt.Sprintf("%s%v", cacheAnnouncementAnnouncementIdPrefix, announcementId)
	var resp Announcement
	err := m.QueryRowIndexCtx(ctx, &resp, announcementAnnouncementIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `announcement_id` = ? limit 1", announcementRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, announcementId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAnnouncementModel) Insert(ctx context.Context, data *Announcement) (sql.Result, error) {
	announcementAnnouncementIdKey := fmt.Sprintf("%s%v", cacheAnnouncementAnnouncementIdPrefix, data.AnnouncementId)
	announcementIdKey := fmt.Sprintf("%s%v", cacheAnnouncementIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, announcementRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.AnnouceUserId, data.AnnouncementId, data.Title, data.DeletedAt)
	}, announcementAnnouncementIdKey, announcementIdKey)
	return ret, err
}

func (m *defaultAnnouncementModel) Update(ctx context.Context, newData *Announcement) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	announcementAnnouncementIdKey := fmt.Sprintf("%s%v", cacheAnnouncementAnnouncementIdPrefix, data.AnnouncementId)
	announcementIdKey := fmt.Sprintf("%s%v", cacheAnnouncementIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, announcementRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.AnnouceUserId, newData.AnnouncementId, newData.Title, newData.DeletedAt, newData.Id)
	}, announcementAnnouncementIdKey, announcementIdKey)
	return err
}

func (m *defaultAnnouncementModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAnnouncementIdPrefix, primary)
}

func (m *defaultAnnouncementModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", announcementRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAnnouncementModel) tableName() string {
	return m.table
}
