// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package announcement

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	announcementsFieldNames          = builder.RawFieldNames(&Announcements{})
	announcementsRows                = strings.Join(announcementsFieldNames, ",")
	announcementsRowsExpectAutoSet   = strings.Join(stringx.Remove(announcementsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	announcementsRowsWithPlaceHolder = strings.Join(stringx.Remove(announcementsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAnnouncementsIdPrefix             = "cache:announcements:id:"
	cacheAnnouncementsAnnouncementIdPrefix = "cache:announcements:announcementId:"
)

type (
	announcementsModel interface {
		Insert(ctx context.Context, data *Announcements) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Announcements, error)
		FindOneByAnnouncementId(ctx context.Context, announcementId string) (*Announcements, error)
		Update(ctx context.Context, data *Announcements) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAnnouncementsModel struct {
		sqlc.CachedConn
		table string
	}

	Announcements struct {
		Id             int64        `db:"id"`              // 内部主键
		AnnouncementId string       `db:"announcement_id"` // 对象ID (UUIDv7)
		Title          string       `db:"title"`
		Content        string       `db:"content"`
		CreatedAt      time.Time    `db:"created_at"`
		UpdatedAt      time.Time    `db:"updated_at"`
		DeletedAt      sql.NullTime `db:"deleted_at"`
	}
)

func newAnnouncementsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAnnouncementsModel {
	return &defaultAnnouncementsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`announcements`",
	}
}

func (m *defaultAnnouncementsModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	announcementsAnnouncementIdKey := fmt.Sprintf("%s%v", cacheAnnouncementsAnnouncementIdPrefix, data.AnnouncementId)
	announcementsIdKey := fmt.Sprintf("%s%v", cacheAnnouncementsIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, announcementsAnnouncementIdKey, announcementsIdKey)
	return err
}

func (m *defaultAnnouncementsModel) FindOne(ctx context.Context, id int64) (*Announcements, error) {
	announcementsIdKey := fmt.Sprintf("%s%v", cacheAnnouncementsIdPrefix, id)
	var resp Announcements
	err := m.QueryRowCtx(ctx, &resp, announcementsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", announcementsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAnnouncementsModel) FindOneByAnnouncementId(ctx context.Context, announcementId string) (*Announcements, error) {
	announcementsAnnouncementIdKey := fmt.Sprintf("%s%v", cacheAnnouncementsAnnouncementIdPrefix, announcementId)
	var resp Announcements
	err := m.QueryRowIndexCtx(ctx, &resp, announcementsAnnouncementIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `announcement_id` = ? limit 1", announcementsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, announcementId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAnnouncementsModel) Insert(ctx context.Context, data *Announcements) (sql.Result, error) {
	announcementsAnnouncementIdKey := fmt.Sprintf("%s%v", cacheAnnouncementsAnnouncementIdPrefix, data.AnnouncementId)
	announcementsIdKey := fmt.Sprintf("%s%v", cacheAnnouncementsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, announcementsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.AnnouncementId, data.Title, data.Content, data.DeletedAt)
	}, announcementsAnnouncementIdKey, announcementsIdKey)
	return ret, err
}

func (m *defaultAnnouncementsModel) Update(ctx context.Context, newData *Announcements) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	announcementsAnnouncementIdKey := fmt.Sprintf("%s%v", cacheAnnouncementsAnnouncementIdPrefix, data.AnnouncementId)
	announcementsIdKey := fmt.Sprintf("%s%v", cacheAnnouncementsIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, announcementsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.AnnouncementId, newData.Title, newData.Content, newData.DeletedAt, newData.Id)
	}, announcementsAnnouncementIdKey, announcementsIdKey)
	return err
}

func (m *defaultAnnouncementsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAnnouncementsIdPrefix, primary)
}

func (m *defaultAnnouncementsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", announcementsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAnnouncementsModel) tableName() string {
	return m.table
}
