name: service_backend

x-config-env:
  environment:
    # :
    &config-env
    APP_NAME: service_backend

    # Auth:
    AUTH_ACCESS_SECRET: 'your-256-bit-secret'
    AUTH_ACCESS_EXPIRE: 86400

    # Refresh:
    REFRESH_ACCESS_SECRET: 'your-256-bit-secret'
    REFRESH_ACCESS_EXPIRE: 604800

    # SqlxConf:
    DB_DRIVER: mysql
    DB_HOST: mysql
    DB_PORT: 3306
    DB_NAME: service_backend
    DB_USER: service_backend
    DB_PASSWORD: 'service_backend-db-password'
    DB_PARAMS: charset=utf8mb4&parseTime=True&loc=Local
    DB_POLICY: round-robin

    # CacheConf:
    CACHE_REDIS_HOST: redis
    CACHE_REDIS_PORT: 6379
    CACHE_REDIS_TYPE: node
    # CACHE_REDIS_USER: service_backend
    # CACHE_REDIS_PASSWORD: 'service_backend-redis-password'

    # RedisConf:
    REDIS_HOST: redis
    REDIS_PORT: 6379
    REDIS_TYPE: node
    # REDIS_USER: service_backend
    # REDIS_PASSWORD: 'service_backend-redis-password'

    LOG_MODE: file
    LOG_ENCODING: json
    LOG_TIME_FORMAT: ''
    LOG_PATH: 'logs'
    LOG_LEVEL: debug
    LOG_MAX_CONTENT_LENGTH: 1024
    LOG_COMPRESS: true
    LOG_STAT: true
    LOG_KEEP_DAYS: 14
    LOG_STACK_COOLDOWN_MILLIS: 100
    LOG_MAX_BACKUPS: 0
    LOG_MAX_SIZE: 0
    LOG_ROTATION: daily

services:
  mysql:
    image: mysql:8.0
    container_name: service_backend-mysql
    restart: unless-stopped
    ports:
      - "13306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 'your-mysql-root-password'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: service_backend
      MYSQL_USER: service_backend
      MYSQL_PASSWORD: 'service_backend-db-password'
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "service_backend", "-p", "service_backend-db-password" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql
      - ../sql:/docker-entrypoint-initdb.d
      - ../sql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    networks:
      - service_backend

  redis:
    image: redis:8.6.3-alpine
    container_name: service_backend-redis
    restart: unless-stopped
    ports:
      - "16379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "service_backend-redis-password", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data
    networks:
      - service_backend

  service_backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: NephrenRuqInsania/service_backend:latest
    container_name: service_backend
    restart: unless-stopped
    ports:
      - "18888:8888"
    depends_on: [ mysql, redis ]
    environment:
      <<: *config-env
    networks:
      - service_backend

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local

networks:
  service_backend:
    driver: bridge
      
