// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package markdown

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	markdownContentFieldNames          = builder.RawFieldNames(&MarkdownContent{})
	markdownContentRows                = strings.Join(markdownContentFieldNames, ",")
	markdownContentRowsExpectAutoSet   = strings.Join(stringx.Remove(markdownContentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	markdownContentRowsWithPlaceHolder = strings.Join(stringx.Remove(markdownContentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMarkdownContentIdPrefix         = "cache:markdownContent:id:"
	cacheMarkdownContentMarkdownIdPrefix = "cache:markdownContent:markdownId:"
)

type (
	markdownContentModel interface {
		Insert(ctx context.Context, data *MarkdownContent) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*MarkdownContent, error)
		FindOneByMarkdownId(ctx context.Context, markdownId string) (*MarkdownContent, error)
		Update(ctx context.Context, data *MarkdownContent) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMarkdownContentModel struct {
		sqlc.CachedConn
		table string
	}

	MarkdownContent struct {
		Id         int64  `db:"id"`          // 内部主键
		MarkdownId string `db:"markdown_id"` // 对象ID (UUIDv7)
		Content    string `db:"content"`
	}
)

func newMarkdownContentModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMarkdownContentModel {
	return &defaultMarkdownContentModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`markdown_content`",
	}
}

func (m *defaultMarkdownContentModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	markdownContentIdKey := fmt.Sprintf("%s%v", cacheMarkdownContentIdPrefix, id)
	markdownContentMarkdownIdKey := fmt.Sprintf("%s%v", cacheMarkdownContentMarkdownIdPrefix, data.MarkdownId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, markdownContentIdKey, markdownContentMarkdownIdKey)
	return err
}

func (m *defaultMarkdownContentModel) FindOne(ctx context.Context, id int64) (*MarkdownContent, error) {
	markdownContentIdKey := fmt.Sprintf("%s%v", cacheMarkdownContentIdPrefix, id)
	var resp MarkdownContent
	err := m.QueryRowCtx(ctx, &resp, markdownContentIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", markdownContentRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMarkdownContentModel) FindOneByMarkdownId(ctx context.Context, markdownId string) (*MarkdownContent, error) {
	markdownContentMarkdownIdKey := fmt.Sprintf("%s%v", cacheMarkdownContentMarkdownIdPrefix, markdownId)
	var resp MarkdownContent
	err := m.QueryRowIndexCtx(ctx, &resp, markdownContentMarkdownIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `markdown_id` = ? limit 1", markdownContentRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, markdownId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMarkdownContentModel) Insert(ctx context.Context, data *MarkdownContent) (sql.Result, error) {
	markdownContentIdKey := fmt.Sprintf("%s%v", cacheMarkdownContentIdPrefix, data.Id)
	markdownContentMarkdownIdKey := fmt.Sprintf("%s%v", cacheMarkdownContentMarkdownIdPrefix, data.MarkdownId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, markdownContentRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MarkdownId, data.Content)
	}, markdownContentIdKey, markdownContentMarkdownIdKey)
	return ret, err
}

func (m *defaultMarkdownContentModel) Update(ctx context.Context, newData *MarkdownContent) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	markdownContentIdKey := fmt.Sprintf("%s%v", cacheMarkdownContentIdPrefix, data.Id)
	markdownContentMarkdownIdKey := fmt.Sprintf("%s%v", cacheMarkdownContentMarkdownIdPrefix, data.MarkdownId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, markdownContentRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MarkdownId, newData.Content, newData.Id)
	}, markdownContentIdKey, markdownContentMarkdownIdKey)
	return err
}

func (m *defaultMarkdownContentModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMarkdownContentIdPrefix, primary)
}

func (m *defaultMarkdownContentModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", markdownContentRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMarkdownContentModel) tableName() string {
	return m.table
}
