// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package markdown

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	markdownsFieldNames          = builder.RawFieldNames(&Markdowns{})
	markdownsRows                = strings.Join(markdownsFieldNames, ",")
	markdownsRowsExpectAutoSet   = strings.Join(stringx.Remove(markdownsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	markdownsRowsWithPlaceHolder = strings.Join(stringx.Remove(markdownsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMarkdownsIdPrefix         = "cache:markdowns:id:"
	cacheMarkdownsMarkdownIdPrefix = "cache:markdowns:markdownId:"
)

type (
	markdownsModel interface {
		Insert(ctx context.Context, data *Markdowns) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Markdowns, error)
		FindOneByMarkdownId(ctx context.Context, markdownId string) (*Markdowns, error)
		Update(ctx context.Context, data *Markdowns) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMarkdownsModel struct {
		sqlc.CachedConn
		table string
	}

	Markdowns struct {
		Id            int64        `db:"id"`             // 内部主键
		MarkdownId    string       `db:"markdown_id"`    // 对象ID (UUIDv7)
		AuthorId      string       `db:"author_id"`      // 作者 users.user_id (UUIDv7)
		ReviewerId    string       `db:"reviewer_id"`    // 审核人 users.user_id (UUIDv7)
		ReviewStatus  string       `db:"review_status"`  // 审核状态: pending|approved|rejected
		ReviewComment string       `db:"review_comment"` // 审核意见
		Title         string       `db:"title"`
		Summary       string       `db:"summary"`
		CreatedAt     time.Time    `db:"created_at"`
		UpdatedAt     time.Time    `db:"updated_at"`
		DeletedAt     sql.NullTime `db:"deleted_at"`
	}
)

func newMarkdownsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMarkdownsModel {
	return &defaultMarkdownsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`markdowns`",
	}
}

func (m *defaultMarkdownsModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	markdownsIdKey := fmt.Sprintf("%s%v", cacheMarkdownsIdPrefix, id)
	markdownsMarkdownIdKey := fmt.Sprintf("%s%v", cacheMarkdownsMarkdownIdPrefix, data.MarkdownId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, markdownsIdKey, markdownsMarkdownIdKey)
	return err
}

func (m *defaultMarkdownsModel) FindOne(ctx context.Context, id int64) (*Markdowns, error) {
	markdownsIdKey := fmt.Sprintf("%s%v", cacheMarkdownsIdPrefix, id)
	var resp Markdowns
	err := m.QueryRowCtx(ctx, &resp, markdownsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", markdownsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMarkdownsModel) FindOneByMarkdownId(ctx context.Context, markdownId string) (*Markdowns, error) {
	markdownsMarkdownIdKey := fmt.Sprintf("%s%v", cacheMarkdownsMarkdownIdPrefix, markdownId)
	var resp Markdowns
	err := m.QueryRowIndexCtx(ctx, &resp, markdownsMarkdownIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `markdown_id` = ? limit 1", markdownsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, markdownId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMarkdownsModel) Insert(ctx context.Context, data *Markdowns) (sql.Result, error) {
	markdownsIdKey := fmt.Sprintf("%s%v", cacheMarkdownsIdPrefix, data.Id)
	markdownsMarkdownIdKey := fmt.Sprintf("%s%v", cacheMarkdownsMarkdownIdPrefix, data.MarkdownId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, markdownsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MarkdownId, data.AuthorId, data.ReviewerId, data.ReviewStatus, data.ReviewComment, data.Title, data.Summary, data.DeletedAt)
	}, markdownsIdKey, markdownsMarkdownIdKey)
	return ret, err
}

func (m *defaultMarkdownsModel) Update(ctx context.Context, newData *Markdowns) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	markdownsIdKey := fmt.Sprintf("%s%v", cacheMarkdownsIdPrefix, data.Id)
	markdownsMarkdownIdKey := fmt.Sprintf("%s%v", cacheMarkdownsMarkdownIdPrefix, data.MarkdownId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, markdownsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MarkdownId, newData.AuthorId, newData.ReviewerId, newData.ReviewStatus, newData.ReviewComment, newData.Title, newData.Summary, newData.DeletedAt, newData.Id)
	}, markdownsIdKey, markdownsMarkdownIdKey)
	return err
}

func (m *defaultMarkdownsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMarkdownsIdPrefix, primary)
}

func (m *defaultMarkdownsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", markdownsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMarkdownsModel) tableName() string {
	return m.table
}
