// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package markdown

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	markdownReviewInfoFieldNames          = builder.RawFieldNames(&MarkdownReviewInfo{})
	markdownReviewInfoRows                = strings.Join(markdownReviewInfoFieldNames, ",")
	markdownReviewInfoRowsExpectAutoSet   = strings.Join(stringx.Remove(markdownReviewInfoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	markdownReviewInfoRowsWithPlaceHolder = strings.Join(stringx.Remove(markdownReviewInfoFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMarkdownReviewInfoIdPrefix         = "cache:markdownReviewInfo:id:"
	cacheMarkdownReviewInfoMarkdownIdPrefix = "cache:markdownReviewInfo:markdownId:"
)

type (
	markdownReviewInfoModel interface {
		Insert(ctx context.Context, data *MarkdownReviewInfo) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*MarkdownReviewInfo, error)
		FindOneByMarkdownId(ctx context.Context, markdownId string) (*MarkdownReviewInfo, error)
		Update(ctx context.Context, data *MarkdownReviewInfo) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMarkdownReviewInfoModel struct {
		sqlc.CachedConn
		table string
	}

	MarkdownReviewInfo struct {
		Id            int64     `db:"id"`             // 内部主键
		MarkdownId    string    `db:"markdown_id"`    // 对象ID (UUIDv7)
		ReviewerId    string    `db:"reviewer_id"`    // 审核人 users.user_id (UUIDv7)
		ReviewStatus  string    `db:"review_status"`  // 审核状态: pending|approved|rejected
		ReviewComment string    `db:"review_comment"` // 审核意见
		ReviewAt      time.Time `db:"review_at"`
	}
)

func newMarkdownReviewInfoModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMarkdownReviewInfoModel {
	return &defaultMarkdownReviewInfoModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`markdown_review_info`",
	}
}

func (m *defaultMarkdownReviewInfoModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	markdownReviewInfoIdKey := fmt.Sprintf("%s%v", cacheMarkdownReviewInfoIdPrefix, id)
	markdownReviewInfoMarkdownIdKey := fmt.Sprintf("%s%v", cacheMarkdownReviewInfoMarkdownIdPrefix, data.MarkdownId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, markdownReviewInfoIdKey, markdownReviewInfoMarkdownIdKey)
	return err
}

func (m *defaultMarkdownReviewInfoModel) FindOne(ctx context.Context, id int64) (*MarkdownReviewInfo, error) {
	markdownReviewInfoIdKey := fmt.Sprintf("%s%v", cacheMarkdownReviewInfoIdPrefix, id)
	var resp MarkdownReviewInfo
	err := m.QueryRowCtx(ctx, &resp, markdownReviewInfoIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", markdownReviewInfoRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMarkdownReviewInfoModel) FindOneByMarkdownId(ctx context.Context, markdownId string) (*MarkdownReviewInfo, error) {
	markdownReviewInfoMarkdownIdKey := fmt.Sprintf("%s%v", cacheMarkdownReviewInfoMarkdownIdPrefix, markdownId)
	var resp MarkdownReviewInfo
	err := m.QueryRowIndexCtx(ctx, &resp, markdownReviewInfoMarkdownIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `markdown_id` = ? limit 1", markdownReviewInfoRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, markdownId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMarkdownReviewInfoModel) Insert(ctx context.Context, data *MarkdownReviewInfo) (sql.Result, error) {
	markdownReviewInfoIdKey := fmt.Sprintf("%s%v", cacheMarkdownReviewInfoIdPrefix, data.Id)
	markdownReviewInfoMarkdownIdKey := fmt.Sprintf("%s%v", cacheMarkdownReviewInfoMarkdownIdPrefix, data.MarkdownId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, markdownReviewInfoRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MarkdownId, data.ReviewerId, data.ReviewStatus, data.ReviewComment, data.ReviewAt)
	}, markdownReviewInfoIdKey, markdownReviewInfoMarkdownIdKey)
	return ret, err
}

func (m *defaultMarkdownReviewInfoModel) Update(ctx context.Context, newData *MarkdownReviewInfo) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	markdownReviewInfoIdKey := fmt.Sprintf("%s%v", cacheMarkdownReviewInfoIdPrefix, data.Id)
	markdownReviewInfoMarkdownIdKey := fmt.Sprintf("%s%v", cacheMarkdownReviewInfoMarkdownIdPrefix, data.MarkdownId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, markdownReviewInfoRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MarkdownId, newData.ReviewerId, newData.ReviewStatus, newData.ReviewComment, newData.ReviewAt, newData.Id)
	}, markdownReviewInfoIdKey, markdownReviewInfoMarkdownIdKey)
	return err
}

func (m *defaultMarkdownReviewInfoModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMarkdownReviewInfoIdPrefix, primary)
}

func (m *defaultMarkdownReviewInfoModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", markdownReviewInfoRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMarkdownReviewInfoModel) tableName() string {
	return m.table
}
