// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package markdown

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	markdownFieldNames          = builder.RawFieldNames(&Markdown{})
	markdownRows                = strings.Join(markdownFieldNames, ",")
	markdownRowsExpectAutoSet   = strings.Join(stringx.Remove(markdownFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	markdownRowsWithPlaceHolder = strings.Join(stringx.Remove(markdownFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMarkdownIdPrefix         = "cache:markdown:id:"
	cacheMarkdownMarkdownIdPrefix = "cache:markdown:markdownId:"
)

type (
	markdownModel interface {
		Insert(ctx context.Context, data *Markdown) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Markdown, error)
		FindOneByMarkdownId(ctx context.Context, markdownId string) (*Markdown, error)
		Update(ctx context.Context, data *Markdown) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMarkdownModel struct {
		sqlc.CachedConn
		table string
	}

	Markdown struct {
		Id         int64        `db:"id"`          // 内部主键
		MarkdownId string       `db:"markdown_id"` // 对象ID (UUIDv7)
		AuthorId   string       `db:"author_id"`   // 作者 users.user_id (UUIDv7)
		Title      string       `db:"title"`
		Summary    string       `db:"summary"`
		CreatedAt  time.Time    `db:"created_at"`
		UpdatedAt  time.Time    `db:"updated_at"`
		DeletedAt  sql.NullTime `db:"deleted_at"`
	}
)

func newMarkdownModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMarkdownModel {
	return &defaultMarkdownModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`markdown`",
	}
}

func (m *defaultMarkdownModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	markdownIdKey := fmt.Sprintf("%s%v", cacheMarkdownIdPrefix, id)
	markdownMarkdownIdKey := fmt.Sprintf("%s%v", cacheMarkdownMarkdownIdPrefix, data.MarkdownId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, markdownIdKey, markdownMarkdownIdKey)
	return err
}

func (m *defaultMarkdownModel) FindOne(ctx context.Context, id int64) (*Markdown, error) {
	markdownIdKey := fmt.Sprintf("%s%v", cacheMarkdownIdPrefix, id)
	var resp Markdown
	err := m.QueryRowCtx(ctx, &resp, markdownIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", markdownRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMarkdownModel) FindOneByMarkdownId(ctx context.Context, markdownId string) (*Markdown, error) {
	markdownMarkdownIdKey := fmt.Sprintf("%s%v", cacheMarkdownMarkdownIdPrefix, markdownId)
	var resp Markdown
	err := m.QueryRowIndexCtx(ctx, &resp, markdownMarkdownIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `markdown_id` = ? limit 1", markdownRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, markdownId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMarkdownModel) Insert(ctx context.Context, data *Markdown) (sql.Result, error) {
	markdownIdKey := fmt.Sprintf("%s%v", cacheMarkdownIdPrefix, data.Id)
	markdownMarkdownIdKey := fmt.Sprintf("%s%v", cacheMarkdownMarkdownIdPrefix, data.MarkdownId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, markdownRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MarkdownId, data.AuthorId, data.Title, data.Summary, data.DeletedAt)
	}, markdownIdKey, markdownMarkdownIdKey)
	return ret, err
}

func (m *defaultMarkdownModel) Update(ctx context.Context, newData *Markdown) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	markdownIdKey := fmt.Sprintf("%s%v", cacheMarkdownIdPrefix, data.Id)
	markdownMarkdownIdKey := fmt.Sprintf("%s%v", cacheMarkdownMarkdownIdPrefix, data.MarkdownId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, markdownRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MarkdownId, newData.AuthorId, newData.Title, newData.Summary, newData.DeletedAt, newData.Id)
	}, markdownIdKey, markdownMarkdownIdKey)
	return err
}

func (m *defaultMarkdownModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMarkdownIdPrefix, primary)
}

func (m *defaultMarkdownModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", markdownRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMarkdownModel) tableName() string {
	return m.table
}
